# RATING PREDICTION PROJECT:

Submitted by **GAIRIK** Internship

<span class="image"></span>

## PROBLEM STATEMENT:

**We have a client who has a website where people write different
reviews for technical products. Now they are adding a new feature to
their website i.e. The reviewer will have to add stars(rating) as well
with the review. The rating is out 5 stars and it only has 5 options
available 1 star, 2 stars, 3 stars, 4 stars, 5 stars. Now they want to
predict ratings for the reviews which were written in the past and they
don’t have a rating. So, we have to build an application which can
predict the rating by seeing the review.**

### 1)Data Collection Phase:

**You have to scrape at least 20000 rows of data. You can scrape more
data as well, it’s up to you. more the data better the model In this
section you need to scrape the reviews of different laptops, Phones,
Headphones, smart watches, Professional Cameras, Printers, Monitors,
Home theater, Router from different ecommerce websites. Basically, we
need these columns**

-   **1) reviews of the product.**
-   **2) rating of the product.**

**You can fetch other data as well, if you think data can be useful or
can help in the project.It completely depends on your imagination or
assumption.**

### 2)Model Building Phase:

**After collecting the data, you need to build a machine learning model.
Before model building do all data preprocessing steps involving NLP. Try
different models with different hyper parameters and select the best
model.** **Follow the complete life cycle of data science. Include all
the steps like**

-   **1. Data Cleaning**
-   **2. Exploratory Data Analysis**
-   **3. Data Preprocessing**
-   **4. Model Building**
-   **5. Model Evaluation**
-   **6. Selecting the best model**

# Importing Necessary Libraries:

# Importing Scrapped Dataset:

I have imported the collected data which was in csv format and stored it
as a dataframe. We can see the first 5 and last 5 observations of the
dataset and it looks good also we have all string valued columns. In
this perticular dataset we have about 114491 rows and 3 columns Unnamed:
0 is the index column of csv file so let's drop that column. Since
**Ratings** is my target column and it is a categorical column with 5
categories so this problem is a **Multi Classification Problem**.

### Feature Information:

-   Review_Title : Title of the Review.
-   Review_Text : Text Content of the Review.
-   Ratings : Ratings out of 5 stars.

# Exploratory Data Analysis \[EDA\]:

Since Unnamed: 0 is the index column of csv file so let's drop that
column as it will not help us in our predictions.

There are 114491 Rows and 3 Columns in the dataset

So there are 114491 rows and 3 columns in the dataset.

Columns present in the dataset are:
 Index(['Review_Title', 'Review_Text', 'Ratings'], dtype='object')

So above 3 are the column names in the dataset.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114491 entries, 0 to 114490
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype 
---  ------        --------------   ----- 
 0   Review_Title  98879 non-null   object
 1   Review_Text   100658 non-null  object
 2   Ratings       98880 non-null   object
dtypes: object(3)
memory usage: 2.6+ MB

By observing the info we can say that there are some null values in the
dataset and all the columns are of object data type which means all the
entries are string entries.

Null values in the dataset: 
 Review_Title    15612
Review_Text     13833
Ratings         15611
dtype: int64

So we have a huge number of nan values in the dataset. Let's replace
them using imputation methods.

Now we can clear have a look on null values by using visualization.

# Replacing nan values using imputation method:

0    Wonderful
dtype: object

So the highest occuring Review_Title is Wonderful, we have to replace
the nan values in Review_Title column with it's mode.

0    Good
dtype: object

So the highest occuring Review_Text is Good, we have to replace the nan
values in Review_Text column with it's mode.

5                     19085
5.0 out of 5 stars    16301
1.0 out of 5 stars    14598
4.0 out of 5 stars    14261
3.0 out of 5 stars    12313
2.0 out of 5 stars    10726
4                      6470
1                      2249
3                      2098
2                       779
Name: Ratings, dtype: int64

Since the highes count in Ratings column is for 5 followed by 5.0 out of
5 starts and they both are same so it is clear the mode for Ratings
column is 5.

0    5
dtype: object

Null values in the dataset: 
 Review_Title    0
Review_Text     0
Ratings         0
dtype: int64

Now successfully we have replaced all the nan values using imputation
method.

### Let's have a look into target column:

array(['2.0 out of 5 stars', '3.0 out of 5 stars', '1.0 out of 5 stars',
       '5.0 out of 5 stars', '5', '4.0 out of 5 stars', '4', '3', '1',
       '2'], dtype=object)

Looking the above entries in target column we came to know that we need
to replace the string entries to there respective values(stars).

array([2, 3, 1, 5, 4])

Now the target column looks good for our analysis.

### Now let's combine Review_Title and Review_Text to make a single column Review:

Since we have obtained Review from Review_Title and Review_Text let's
drop Review_Title and Review_Text. If not they'll create
multicolinearity issue.

### Let's have a look into our Review column and see first 2 entries how the data looks:

"Think twice before going for it \n  &nbsp;Pros<br>-----<br>- Very light weight<br>- Screen brightness and clarity is awesome<br><br>Cons<br>------<br>- Speaker quality is horrible. Cannot use for calls at all. Crackling noise takes you to vinyl days.<br>- Body is not sturdy. The piece I received was slightly bent at the base, making the laptop wobble when I type.<br>- The bottom screw was hanging out with the thread gone due to incorrect tightening (so much for Japanese craftmanship)<br><br>Recommend to not purchase. It's not worth at this price point.\n"

'Overpriced \n  Overpriced for this mediocre product with no brand value, better to check out other products in reputed brands like dell, Hp, Asus\n'

By observing the Reviews we can say that there are many words, numbers,
as well as punctuations which are not important for our predictions. So
we need to do good text processing.

# Text Processing:

### Let's have a look into our text again:

'think twice before going for it    nbsppros   very light weight  screen brightness and clarity is awesome  cons   speaker quality is horrible cannot use for calls at all crackling noise takes you to vinyl days  body is not sturdy the piece i received was slightly bent at the base making the laptop wobble when i type  the bottom screw was hanging out with the thread gone due to incorrect tightening so much for japanese craftmanship  recommend to not purchase it is not worth at this price point '

'overpriced    overpriced for this mediocre product with no brand value better to check out other products in reputed brands like dell hp asus '

Now the data looks far better than previous.And we have successfully
removed punctuations and unwanted text from our text and lowercased all
the text data.

# Removing StopWords:

'think twice going nbsppros light weight screen brightness clarity awesome cons speaker quality horrible cannot use calls crackling noise takes vinyl days body sturdy piece received slightly bent base making laptop wobble type bottom screw hanging thread gone due incorrect tightening much japanese craftmanship recommend purchase worth price point'

'overpriced overpriced mediocre product brand value better check products reputed brands like dell hp asus'

Now we have removed all stop words from the text data.

# Lemmatization:

'think twice go nbsppros light weight screen brightness clarity awesome con speaker quality horrible can not use call crackle noise take vinyl day body sturdy piece receive slightly bent base make laptop wobble type bottom screw hang thread go due incorrect tighten much japanese craftmanship recommend purchase worth price point'

'overprice overpriced mediocre product brand value well check product repute brand like dell hp asus'

So now we have removed the inflectional endings and left out with the
base or dictionary form of a word.

# Text Normalization - Standardization:

'think twice go nbsppros light weight screen brightness clarity awesome con speaker quality horrible can not use call crackle noise take vinyl day body sturdy piece receive slightly bent base make laptop wobble type bottom screw hang thread go due incorrect tighten much japanese craftmanship recommend purchase worth price point'

'overprice overpriced mediocre product brand value well check product repute brand like dell hp asus'

Finally I have defined a function scrub_words for removing the noise
from the text. It will remove any html markups, digits and white spaces
from the text.

Now We did all the text-processing steps and got required input for our
model. We will get into Visualization part now.

# Visualization:

## i) Word Counts:

By observing the histogram we can clearly see that most of our text is
having the number of words in the range of 0 to 200, But some of the
reviews are too lengthy which may act like outliers in our data.

## ii) Character count:

Above plot represents histogram for character count of Review text,
which is quite similar to the histogram of word count.

# Removing Outliers:

As we know that some of the review are too lengthy, so i have to treat
them as outliers and remove them using z_score method.

(114491, 4)

(112971, 4)

Great by removing the outliers we are loosing 1.3% of data which is very
less and it is in acceptable range.

## Plotting histograms for word count and character counts again after removing outliers:

After plotting histograms for word counts and character counts and after
removing outliers we can see we are left out with good range of number
of words and characters.

# iii) Top 30 most frequently occuring words:

By seeing the above plot we can see that Good, prodout, quality......are
occurring frequently.

# iv) Top 30 Rare words:

Above list of words are have rare occurance in Review.

# v) Word cloud:

### Observations:

-   From the above plots we can clearly see the words which are
    indication of Reviewer's opinion on products.
-   Here most frequent words used for each Rating is displayed in the
    word cloud.

5    50243
4    20378
1    16687
3    14258
2    11405
Name: Ratings, dtype: int64

# Model Building and Evaluation:

# Converting text data into vectors using Tfidf Vectorizer:

# Splitting the data into train and test:

# Data Balancing:

x_train (84728, 150000)
x_test (28243, 150000)
y_train (84728,)
y_test (28243,)

Now let's do oversmapling in order to make data balanced.

5    50243
4    20378
1    16687
3    14258
2    11405
Name: Ratings, dtype: int64

The number of classes before fitCounter({5: 37633, 4: 15304, 1: 12568, 3: 10687, 2: 8536})

So we have maximum count 37633 for 5ratings hence will over sample
mannually all the ratings to the mark 37633.

The number of classes before fitCounter({5: 37633, 4: 15304, 1: 12568, 3: 10687, 2: 8536})
The number of classes after fit Counter({3: 37633, 2: 37633, 1: 37633, 4: 37633, 5: 37633})

So now we have successfully balanced the data. Let's proceed with model
building.

******************************LogisticRegression******************************
Accuracy Score: 73.07297383422441
---------------------------------------------------
CLASSIFICATION REPORT : 
               precision    recall  f1-score   support

           1       0.70      0.77      0.73      4119
           2       0.51      0.49      0.50      2869
           3       0.54      0.54      0.54      3571
           4       0.60      0.68      0.64      5074
           5       0.92      0.85      0.88     12610

    accuracy                           0.73     28243
   macro avg       0.65      0.67      0.66     28243
weighted avg       0.74      0.73      0.73     28243

Confusion Matrix : 
 [[ 3164   538   284    87    46]
 [  702  1403   511   208    45]
 [  385   493  1939   629   125]
 [  132   207   565  3438   732]
 [  134   127   285  1370 10694]]

******************************LinearSVC******************************
Accuracy Score: 76.30209255390716
----------------------------

I have created 6 different classification algorithms. Great, among all
these algorithms all are giving good accuracies.

# Cross validation score:

******************************LogisticRegression******************************
Cross validation score : 58.2556585318356
******************************LinearSVC******************************
Cross validation score : 57.08544670756211
******************************DecisionTreeClassifier******************************
Cross validation score : 50.68291862513389
******************************SGDClassifier******************************
Cross validation score : 58.57343920121093
******************************RandomForestClassifier******************************
Cross validation score : 58.619468713209585
******************************XGBClassifier******************************
Cross validation score : 58.42295810429224

Great all our algorithms are giving good cv scores.Among these
algorithms I am selecting SGD Classifier as best fitting algorithm for
our final model as it is giving least difference between accuracy and cv
score.

# HyperParameter Tuning:

Fitting 3 folds for each of 12 candidates, totalling 36 fits
[CV 1/3; 1/12] START loss=hinge, n_jobs=-1, penalty=l2..........................
[CV 1/3; 1/12] END loss=hinge, n_jobs=-1, penalty=l2;, score=0.708 total time= 2.2min
[CV 2/3; 1/12] START loss=hinge, n_jobs=-1, penalty=l2..........................
[CV 2/3; 1/12] END loss=hinge, n_jobs=-1, penalty=l2;, score=0.787 total time=   4.4s
[CV 3/3; 1/12] START loss=hinge, n_jobs=-1, penalty=l2..........................
[CV 3/3; 1/12] END loss=hinge, n_jobs=-1, penalty=l2;, score=0.791 total time=   4.4s
[CV 1/3; 2/12] START loss=hinge, n_jobs=-1, penalty=l1..........................
[CV 1/3; 2/12] END loss=hinge, n_jobs=-1, penalty=l1;, score=0.524 total time=   7.2s
[CV 2/3; 2/12] START loss=hinge, n_jobs=-1, penalty=l1..........................
[CV 2/3; 2/12] END loss=hinge, n_jobs=-1, penalty=l1;, score=0.580 total time=   7.5s
[CV 3/3; 2/12] START loss=hinge, n_jobs=-1, penalty=l1..........................
[CV 3/3; 2/12] END loss

GridSearchCV(cv=3, estimator=SGDClassifier(),
             param_grid={'loss': ['hinge', 'squared_hinge'], 'n_jobs': [-1, 1],
                         'penalty': ['l2', 'l1', 'elasticnet']},
             verbose=10)

{'loss': 'squared_hinge', 'n_jobs': -1, 'penalty': 'l1'}

# Final Model:

Accuracy Score : 68.71083100237227

Confusion Matrix : 
 [[ 2716   651   403   192   157]
 [  649  1291   490   273   166]
 [  433   502  1753   553   330]
 [  223   292   592  2956  1011]
 [  186   201   430  1103 10690]]


CLASSIFICATION REPORT : 
               precision    recall  f1-score   support

           1       0.65      0.66      0.65      4119
           2       0.44      0.45      0.44      2869
           3       0.48      0.49      0.48      3571
           4       0.58      0.58      0.58      5074
           5       0.87      0.85      0.86     12610

    accuracy                           0.69     28243
   macro avg       0.60      0.61      0.60     28243
weighted avg       0.69      0.69      0.69     28243


After hyperparameter tuning we are unable to improved our model
accuracy.

# Model Saving:

['Ratings_RP.pkl']

Finally I have saved the model into .pkl file.

# Conclusion:

### Key findings of the study :

-   In this project I have collected data of reviews and ratings for
    different products from amazon.in and flipkart.com.
-   Then I have done different text processing for reviews column and
    chose equal number of text from each rating class to eliminate
    problem of imbalance.
-   By doing different EDA steps I have analyzed the text. We have
    checked frequently occurring words in our data as well as rarely
    occurring words.
-   After all these steps I have built function to train different
    algorithms and using various evaluation metrics I have selected
    SGDClassifier for our final model.
-   Finally by doing hyperparameter tuning we got optimum parameters for
    our final model. And finally we got good accuracy score for our
    final model.

### Limitations of this work and scope for the future work :

As we know the content of text in reviews is totally depends on the
reviewer and they may rate differently which is totally depends on that
particular person. So it is difficult to predict ratings based on the
reviews with higher accuracies. Still we can improve our accuracy by
fetching more data and by doing extensive hyperparameter tuning.

<span class="image"></span>